"""SQL deployment exporter for Spark and Databricks targets.

This module wraps datacontract-cli's SQL exporter for base DDL generation and
adds a small ContractHub-specific compatibility layer:

- use physical names for table/column DDL when requested
- support Unity Catalog table prefixes for Databricks deployments
- compile a small subset of ODCS library quality rules into Databricks-native
  constraints when the target SQL server type is `databricks`

Constraint mapping is intentionally limited to rules that can be expressed as
deterministic row-level Databricks constraints:
- property-level `nullValues mustBe 0` -> `ALTER COLUMN ... SET NOT NULL`
- property-level `invalidValues mustBe 0` + `validValues` -> `CHECK IN (...)`
- property-level `invalidValues mustBe 0` + `pattern` -> `CHECK RLIKE ...`

Precedence rule:
- `SchemaProperty.required=True` is handled first by datacontract-cli's base SQL
  exporter, which emits a column-level `NOT NULL`.
- ContractHub only adds a quality-derived `ALTER COLUMN ... SET NOT NULL` when
  the field is not already required, to avoid duplicate nullability constraints.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, Optional, Union

from datacontract.export.exporter import ExportFormat
from datacontract.export.exporter_factory import exporter_factory
from open_data_contract_standard.model import (
    CustomProperty,
    DataQuality,
    OpenDataContractStandard,
    SchemaObject,
    SchemaProperty,
    Server,
)
from contracthub.utils.schema_utils import contract_to_model

ContractInput = Union[OpenDataContractStandard, Dict[str, Any], str, Path]


class SparkSqlContractExporter:
    """SDK-style exporter for Spark and Databricks DDL generation."""

    def __init__(self, logger: Optional[logging.Logger] = None) -> None:
        self.logger = logger or logging.getLogger(self.__class__.__name__)

    def export_contract(
        self,
        contract: ContractInput,
        *,
        unity_catalog: Optional[str] = None,
        unity_schema: Optional[str] = None,
        unity_server_name: str = "contracthub_target",
        use_physical_names: bool = True,
        sql_server_type: str = "databricks",
    ) -> str:
        """Export deployment DDL and optionally append Databricks constraints.

        Base table DDL is generated by datacontract-cli's SQL exporter.
        ContractHub appends quality-derived constraint SQL only when the target
        server type is `databricks`.

        Nullability precedence:
        - schema-level `required=True` is exported as column `NOT NULL`
        - quality-derived `nullValues mustBe 0` only adds `SET NOT NULL` when
          the schema does not already require the field
        """
        if bool(unity_catalog) != bool(unity_schema):
            raise ValueError("unity_catalog and unity_schema must be provided together")
        if (unity_catalog or unity_schema) and sql_server_type != "databricks":
            raise ValueError(
                "unity_catalog and unity_schema are only supported for sql_server_type=databricks"
            )

        contract_model = _load_contract_model(contract)
        prepared_contract = _prepare_for_sql_export(
            contract_model,
            use_physical_names=use_physical_names,
        )

        export_args: Dict[str, Any] = {}
        if unity_catalog and unity_schema:
            _upsert_unity_server(
                prepared_contract,
                server_name=unity_server_name,
                catalog=unity_catalog,
                schema_name=unity_schema,
            )
            export_args["server"] = unity_server_name
        elif sql_server_type == "databricks":
            # Avoid inheriting non-databricks servers (e.g., postgres) for Spark/Databricks DDL generation.
            prepared_contract.servers = None

        exporter = exporter_factory.create(ExportFormat.sql)
        ddl = exporter.export(
            data_contract=prepared_contract,
            schema_name="all",
            server="",
            sql_server_type=sql_server_type,
            export_args=export_args,
        )

        if sql_server_type in ("databricks", "spark") and prepared_contract.schema_:
            ddl_statements = [stmt for stmt in ddl.split(";\n") if stmt.strip()]
            new_statements = []

            for idx, schema_obj in enumerate(prepared_contract.schema_):
                loc = next(
                    (
                        p.value
                        for p in (schema_obj.customProperties or [])
                        if p.property == "contracthub.table.location"
                    ),
                    None,
                )
                stmt = ddl_statements[idx] if idx < len(ddl_statements) else None
                if stmt and loc:
                    stmt = f"{stmt}\nLOCATION '{loc}'"

                if stmt is not None:
                    new_statements.append(stmt)

            # Keep any trailing statements that might have been added
            for stmt in ddl_statements[len(prepared_contract.schema_) :]:
                new_statements.append(stmt)

            if new_statements:
                ddl = ";\n".join(new_statements) + ";\n"

        if sql_server_type != "databricks":
            return ddl

        table_prefix = (
            f"{unity_catalog}.{unity_schema}." if unity_catalog and unity_schema else ""
        )
        return _append_databricks_quality_constraints(
            ddl, prepared_contract, table_prefix=table_prefix
        )


def export_contract_to_spark_sql(
    contract: ContractInput,
    *,
    unity_catalog: Optional[str] = None,
    unity_schema: Optional[str] = None,
    unity_server_name: str = "contracthub_target",
    use_physical_names: bool = True,
    sql_server_type: str = "databricks",
) -> str:
    exporter = SparkSqlContractExporter()
    return exporter.export_contract(
        contract=contract,
        unity_catalog=unity_catalog,
        unity_schema=unity_schema,
        unity_server_name=unity_server_name,
        use_physical_names=use_physical_names,
        sql_server_type=sql_server_type,
    )


def _load_contract_model(contract: ContractInput) -> OpenDataContractStandard:
    return contract_to_model(contract)


def _prepare_for_sql_export(
    contract: OpenDataContractStandard,
    *,
    use_physical_names: bool,
) -> OpenDataContractStandard:
    prepared = OpenDataContractStandard.model_validate(
        contract.model_dump(by_alias=True, exclude_none=True)
    )

    for schema_obj in prepared.schema_ or []:
        if use_physical_names and schema_obj.physicalName:
            schema_obj.name = schema_obj.physicalName

        for prop in _iter_schema_properties(schema_obj.properties or []):
            if use_physical_names and prop.physicalName:
                prop.name = prop.physicalName
            _ensure_physical_type_custom_property(prop)

    return prepared


def _iter_schema_properties(properties: list[SchemaProperty]) -> list[SchemaProperty]:
    visited: list[SchemaProperty] = []
    stack = list(properties)
    while stack:
        item = stack.pop()
        visited.append(item)
        if item.properties:
            stack.extend(item.properties)
        if item.items is not None:
            stack.append(item.items)
    return visited


def _ensure_physical_type_custom_property(prop: SchemaProperty) -> None:
    if not prop.physicalType:
        return
    existing = prop.customProperties or []
    if any(cp.property == "physicalType" for cp in existing):
        return
    existing.append(CustomProperty(property="physicalType", value=prop.physicalType))
    prop.customProperties = existing


def _upsert_unity_server(
    contract: OpenDataContractStandard,
    *,
    server_name: str,
    catalog: str,
    schema_name: str,
) -> None:
    servers = list(contract.servers or [])
    replacement = Server(
        **{
            "server": server_name,
            "type": "databricks",
            "catalog": catalog,
            "schema": schema_name,
        }
    )

    replaced = False
    for idx, server in enumerate(servers):
        if server.server == server_name:
            servers[idx] = replacement
            replaced = True
            break

    if not replaced:
        servers.append(replacement)
    contract.servers = servers


def _append_databricks_quality_constraints(
    ddl: str,
    contract: OpenDataContractStandard,
    *,
    table_prefix: str,
) -> str:
    """Append supported Databricks constraint statements to base DDL."""
    statements = _collect_databricks_quality_constraints(
        contract, table_prefix=table_prefix
    )
    if not statements:
        return ddl
    suffix = "\n\n".join(statements)
    return f"{ddl.rstrip()}\n\n{suffix}\n"


def _collect_databricks_quality_constraints(
    contract: OpenDataContractStandard,
    *,
    table_prefix: str,
) -> list[str]:
    """Collect deterministic Databricks constraint SQL from property-level ODCS quality rules."""
    statements: list[str] = []
    seen: set[str] = set()

    for schema_obj in contract.schema_ or []:
        table_name = f"{table_prefix}{schema_obj.name}"
        for prop in schema_obj.properties or []:
            for statement in _property_quality_constraints_sql(
                schema_obj, prop, table_name
            ):
                if statement in seen:
                    continue
                seen.add(statement)
                statements.append(statement)

    return statements


def _property_quality_constraints_sql(
    schema_obj: SchemaObject,
    prop: SchemaProperty,
    table_name: str,
) -> list[str]:
    """Compile supported property-level quality rules into Databricks SQL."""
    statements: list[str] = []

    for rule in prop.quality or []:
        if not _is_library_rule(rule):
            continue

        metric = str(rule.metric or rule.rule or "").strip()
        if metric == "nullValues" and _must_be_zero(rule.mustBe):
            if not prop.required:
                statements.append(
                    f"ALTER TABLE {table_name}\n"
                    f"  ALTER COLUMN {prop.name} SET NOT NULL;"
                )
            continue

        if metric != "invalidValues" or not _must_be_zero(rule.mustBe):
            continue

        arguments = rule.arguments or {}
        valid_values = arguments.get("validValues")
        pattern = arguments.get("pattern")

        if isinstance(valid_values, list) and valid_values:
            constraint_name = _constraint_name(
                schema_obj.name, prop.name, "valid_values"
            )
            values_sql = ", ".join(_sql_literal(value) for value in valid_values)
            statements.append(
                f"ALTER TABLE {table_name}\n"
                f"  ADD CONSTRAINT {constraint_name} CHECK ({prop.name} IN ({values_sql}));"
            )
            continue

        if isinstance(pattern, str) and pattern.strip():
            constraint_name = _constraint_name(schema_obj.name, prop.name, "pattern")
            statements.append(
                f"ALTER TABLE {table_name}\n"
                f"  ADD CONSTRAINT {constraint_name} CHECK ({prop.name} RLIKE {_sql_literal(pattern)});"
            )

    return statements


def _is_library_rule(rule: DataQuality) -> bool:
    """Return True when the quality rule is an ODCS library metric."""
    explicit_type = str(rule.type or "").strip()
    if explicit_type:
        return explicit_type == "library"
    return bool(rule.metric or rule.rule)


def _must_be_zero(value: Any) -> bool:
    """Return True when the rule threshold is an exact zero-like value."""
    if value is None:
        return False
    if isinstance(value, bool):
        return False
    if isinstance(value, (int, float)):
        return value == 0
    if isinstance(value, str):
        return value.strip() in {"0", "0.0"}
    return False


def _constraint_name(table_name: str, column_name: str, suffix: str) -> str:
    """Build a deterministic Databricks constraint name."""
    raw = f"chk_{table_name}_{column_name}_{suffix}".lower()
    sanitized = "".join(char if char.isalnum() else "_" for char in raw)
    while "__" in sanitized:
        sanitized = sanitized.replace("__", "_")
    return sanitized.strip("_")


def _sql_literal(value: Any) -> str:
    """Convert Python values into Databricks SQL literals."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"
